@PerfectBreakfast.API_HostAddress = http://localhost:5198

POST {{PerfectBreakfast.API_HostAddress}}/account/login
Accept: application/json
Content-Type: application/json

{
  "email": "viethungdev23@gmail.com",
  "password": "Abc@123"
}
###

POST {{PerfectBreakfast.API_HostAddress}}/account/register
Accept: application/json
Content-Type: application/json

{
  "email": "viethungdev23@gmail.com",
  "password": "Abc@123"
}
