name: build and deploy to DockerHub viethungdev23 

on:
  push:
    branches: 
      - prod
  workflow_dispatch: 

jobs:
  build:
    runs-on: hehe # run bằng host tự tạo của toi
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x' # Sửa đổi tương ứng với phiên bản .NET của bạn
          include-prerelease: true
          
      - name: Build
        run: dotnet build --configuration Release
  
  deploy:
    runs-on: hehe
    needs: build
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/PerfectBreakfast.API/
          push: true
          tags: viethungdev23/backend-dotnet8:latest

    # steps:
    #   - uses: actions/checkout@v3

    #   - name: Build and push Docker image
    #     uses: mr-smithers-excellent/docker-build-push@v6
    #     with:
    #       image: viethungdev23/backend-dotnet8
    #       tags: latest
    #       registry: docker.io
    #       dockerfile: ./src/PerfectBreakfast.API/Dockerfile
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}    
